INSERT INTO "credit_top_up_products" (
  "id",
  "code",
  "name",
  "creditAmount",
  "basePrice",
  "discountRate",
  "promotionName",
  "promotionStartsAt",
  "promotionEndsAt",
  "description",
  "isActive",
  "sortOrder",
  "updatedAt"
) VALUES
  (
    'credit_product_100',
    'CREDIT_150',
    '스타터',
    150,
    20000,
    0,
    NULL,
    NULL,
    NULL,
    '자동출제 약 100문항을 생성할 수 있는 SMOAT AI 크레딧 디지털 이용권입니다.',
    true,
    10,
    CURRENT_TIMESTAMP
  ),
  (
    'credit_product_300',
    'CREDIT_450',
    '스탠다드',
    450,
    33000,
    0,
    NULL,
    NULL,
    NULL,
    '자동출제 약 300문항을 생성할 수 있는 SMOAT AI 크레딧 디지털 이용권입니다.',
    true,
    20,
    CURRENT_TIMESTAMP
  ),
  (
    'credit_product_500',
    'CREDIT_1500',
    '프리미엄',
    1500,
    89000,
    0,
    NULL,
    NULL,
    NULL,
    '자동출제 약 1,000문항을 생성할 수 있는 SMOAT AI 크레딧 디지털 이용권입니다.',
    true,
    30,
    CURRENT_TIMESTAMP
  ),
  (
    'credit_product_1000',
    'CREDIT_4500',
    '엔터프라이즈',
    4500,
    249000,
    0,
    NULL,
    NULL,
    NULL,
    '자동출제 약 3,000문항을 생성할 수 있는 SMOAT AI 크레딧 디지털 이용권입니다.',
    true,
    40,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("id") DO UPDATE SET
  "code" = EXCLUDED."code",
  "name" = EXCLUDED."name",
  "creditAmount" = EXCLUDED."creditAmount",
  "basePrice" = EXCLUDED."basePrice",
  "discountRate" = EXCLUDED."discountRate",
  "promotionName" = EXCLUDED."promotionName",
  "promotionStartsAt" = EXCLUDED."promotionStartsAt",
  "promotionEndsAt" = EXCLUDED."promotionEndsAt",
  "description" = EXCLUDED."description",
  "isActive" = EXCLUDED."isActive",
  "sortOrder" = EXCLUDED."sortOrder",
  "updatedAt" = CURRENT_TIMESTAMP;
