// AUTO-GENERATED by scripts/demo/manifest.ts — do not edit by hand.
export type GuideMark =
  | { tMs: number; type: "caption"; text: string; subtitle?: string }
  | { tMs: number; type: "caption-clear" }
  | { tMs: number; type: "zoom"; rect: { x: number; y: number; width: number; height: number }; scale?: number }
  | { tMs: number; type: "zoom-out" }
  | { tMs: number; type: "highlight"; rect: { x: number; y: number; width: number; height: number } }
  | { tMs: number; type: "chapter"; text: string };

export type GuideEntry = { flow: string; src: string; durationMs: number; fps: number; marks: GuideMark[] };

export const GUIDE_FLOWS: GuideEntry[] = [];
