import type { PaperTemplate } from "./types";

export const TEMPLATE_META: Record<
  PaperTemplate,
  { label: string; description: string; accent: string; swatch: string }
> = {
  clean: {
    label: "클린 내신형",
    description: "파란 포인트와 넓은 여백의 정돈된 내신 시험지",
    accent: "border-blue-300 bg-blue-50 text-blue-700",
    swatch: "from-blue-500 to-sky-400",
  },
  mock: {
    label: "모의고사형",
    description: "흑백 신문식 헤더와 조밀한 2단 문항 흐름",
    accent: "border-slate-400 bg-slate-100 text-slate-800",
    swatch: "from-slate-900 to-slate-500",
  },
  worksheet: {
    label: "워크시트형",
    description: "초록 포인트, 풀이 공간과 교사용 메모 강조",
    accent: "border-emerald-300 bg-emerald-50 text-emerald-700",
    swatch: "from-emerald-500 to-teal-400",
  },
  minimal: {
    label: "미니멀",
    description: "얇은 선과 낮은 채도로 텍스트 밀도 우선",
    accent: "border-zinc-300 bg-zinc-50 text-zinc-700",
    swatch: "from-zinc-500 to-stone-300",
  },
  academy: {
    label: "학원 브랜드형",
    description: "로고와 남색 헤더가 살아나는 배포용 시험지",
    accent: "border-indigo-300 bg-indigo-50 text-indigo-700",
    swatch: "from-indigo-700 to-cyan-500",
  },
  modern: {
    label: "모던 컬러형",
    description: "보라 포인트와 카드형 지문으로 선명한 디자인",
    accent: "border-violet-300 bg-violet-50 text-violet-700",
    swatch: "from-violet-600 to-fuchsia-400",
  },
  classic: {
    label: "클래식 원고형",
    description: "와인 컬러와 세리프 감성의 차분한 지면",
    accent: "border-rose-300 bg-rose-50 text-rose-800",
    swatch: "from-rose-800 to-amber-500",
  },
  colorband: {
    label: "컬러 밴드형",
    description: "상단 색상 띠와 번호 배지로 빠르게 읽히는 구성",
    accent: "border-cyan-300 bg-cyan-50 text-cyan-800",
    swatch: "from-cyan-500 to-lime-400",
  },
};

export const TEMPLATE_VISUALS: Record<
  PaperTemplate,
  {
    pageClass: string;
    innerClass: string;
    headerClass: string;
    headerLineClass: string;
    subtitleClass: string;
    titleClass: string;
    infoClass: string;
    instructionsClass: string;
    continuedHeaderClass: string;
    mainClass: string;
    passageTitleClass: string;
    passageClass: string;
    itemClass: string;
    numberClass: string;
    metaClass: string;
    questionClass: string;
    optionNumberClass: string;
    optionRowClass: string;
    answerLineClass: string;
    teacherNoteClass: string;
    footerClass: string;
    logoFrameClass: string;
  }
> = {
  clean: {
    pageClass: "bg-white text-slate-950 ring-slate-200",
    innerClass: "",
    headerClass: "",
    headerLineClass: "border-slate-900",
    subtitleClass: "text-blue-700",
    titleClass: "text-slate-950",
    infoClass: "text-slate-700 [&>div]:border-slate-300",
    instructionsClass: "text-slate-600",
    continuedHeaderClass: "border-slate-200 text-slate-400",
    mainClass: "",
    passageTitleClass: "text-slate-700",
    passageClass: "border-slate-900/80 bg-white",
    itemClass: "",
    numberClass: "text-slate-950",
    metaClass: "text-slate-500",
    questionClass: "text-slate-950",
    optionNumberClass: "text-slate-800",
    optionRowClass: "",
    answerLineClass: "border-slate-300",
    teacherNoteClass: "bg-amber-50 text-amber-800",
    footerClass: "text-slate-400",
    logoFrameClass: "border-slate-200 bg-white",
  },
  mock: {
    pageClass: "bg-white text-black ring-slate-300",
    innerClass: "",
    headerClass: "",
    headerLineClass: "border-black border-b-2",
    subtitleClass: "text-black",
    titleClass: "font-serif text-black",
    infoClass: "text-black [&>div]:border-black",
    instructionsClass: "text-black",
    continuedHeaderClass: "border-black text-black",
    mainClass: "font-serif",
    passageTitleClass: "text-black",
    passageClass: "border-black bg-white",
    itemClass: "",
    numberClass: "font-serif text-black",
    metaClass: "text-zinc-700",
    questionClass: "font-serif text-black",
    optionNumberClass: "text-black",
    optionRowClass: "",
    answerLineClass: "border-zinc-500",
    teacherNoteClass: "bg-zinc-100 text-zinc-900",
    footerClass: "text-black",
    logoFrameClass: "border-black bg-white",
  },
  worksheet: {
    pageClass: "bg-emerald-50/25 text-emerald-950 ring-emerald-200",
    innerClass: "",
    headerClass: "rounded-xl bg-white/80 px-3 py-3 ring-1 ring-emerald-100",
    headerLineClass: "border-emerald-500",
    subtitleClass: "text-emerald-700",
    titleClass: "text-emerald-950",
    infoClass: "text-emerald-900 [&>div]:border-emerald-200",
    instructionsClass: "text-emerald-800",
    continuedHeaderClass: "border-emerald-200 text-emerald-600",
    mainClass: "",
    passageTitleClass: "text-emerald-800",
    passageClass: "border-emerald-300 bg-white/80",
    itemClass: "",
    numberClass: "text-emerald-700",
    metaClass: "text-emerald-600",
    questionClass: "text-emerald-950",
    optionNumberClass: "text-emerald-700",
    optionRowClass: "",
    answerLineClass: "border-emerald-300",
    teacherNoteClass: "bg-amber-100 text-amber-900",
    footerClass: "text-emerald-500",
    logoFrameClass: "border-emerald-200 bg-white",
  },
  minimal: {
    pageClass: "bg-white text-zinc-950 ring-zinc-200",
    innerClass: "",
    headerClass: "",
    headerLineClass: "border-zinc-300",
    subtitleClass: "text-zinc-500",
    titleClass: "font-semibold text-zinc-950",
    infoClass: "text-zinc-600 [&>div]:border-zinc-200",
    instructionsClass: "text-zinc-500",
    continuedHeaderClass: "border-zinc-200 text-zinc-400",
    mainClass: "",
    passageTitleClass: "text-zinc-500",
    passageClass: "border-zinc-200 bg-white",
    itemClass: "",
    numberClass: "text-zinc-700",
    metaClass: "text-zinc-400",
    questionClass: "text-zinc-950",
    optionNumberClass: "text-zinc-500",
    optionRowClass: "",
    answerLineClass: "border-zinc-200",
    teacherNoteClass: "bg-zinc-100 text-zinc-700",
    footerClass: "text-zinc-300",
    logoFrameClass: "border-zinc-200 bg-white",
  },
  academy: {
    pageClass: "bg-white text-slate-950 ring-indigo-200",
    innerClass: "before:absolute before:inset-x-0 before:top-0 before:h-2 before:bg-indigo-700 before:content-['']",
    headerClass: "rounded-b-xl bg-indigo-50/80 px-3 py-3 ring-1 ring-indigo-100",
    headerLineClass: "border-indigo-500",
    subtitleClass: "text-indigo-700",
    titleClass: "text-indigo-950",
    infoClass: "text-indigo-900 [&>div]:border-indigo-200",
    instructionsClass: "text-indigo-700",
    continuedHeaderClass: "border-indigo-200 text-indigo-600",
    mainClass: "",
    passageTitleClass: "text-indigo-700",
    passageClass: "border-indigo-200 bg-indigo-50/60",
    itemClass: "",
    numberClass: "text-indigo-700",
    metaClass: "text-indigo-500",
    questionClass: "text-slate-950",
    optionNumberClass: "text-indigo-600",
    optionRowClass: "",
    answerLineClass: "border-indigo-200",
    teacherNoteClass: "bg-indigo-50 text-indigo-800",
    footerClass: "text-indigo-400",
    logoFrameClass: "border-indigo-200 bg-white shadow-sm",
  },
  modern: {
    pageClass: "bg-violet-50/25 text-slate-950 ring-violet-200",
    innerClass: "",
    headerClass: "rounded-2xl bg-white px-4 py-3 shadow-sm ring-1 ring-violet-100",
    headerLineClass: "border-violet-300",
    subtitleClass: "text-violet-600",
    titleClass: "text-violet-950",
    infoClass: "text-violet-900 [&>div]:border-violet-200",
    instructionsClass: "text-violet-700",
    continuedHeaderClass: "border-violet-200 text-violet-500",
    mainClass: "",
    passageTitleClass: "text-violet-700",
    passageClass: "border-violet-200 bg-white shadow-[inset_3px_0_0_rgba(124,58,237,0.35)]",
    itemClass: "",
    numberClass: "rounded-full bg-violet-600 px-1.5 py-0.5 text-white",
    metaClass: "text-violet-500",
    questionClass: "text-slate-950",
    optionNumberClass: "text-violet-600",
    optionRowClass: "rounded bg-white/70 px-1 py-0.5",
    answerLineClass: "border-violet-200",
    teacherNoteClass: "bg-violet-50 text-violet-800",
    footerClass: "text-violet-400",
    logoFrameClass: "border-violet-200 bg-white",
  },
  classic: {
    pageClass: "bg-[#fffdf8] text-stone-950 ring-rose-200",
    innerClass: "",
    headerClass: "",
    headerLineClass: "border-rose-900 border-b-2",
    subtitleClass: "text-rose-800",
    titleClass: "font-serif text-rose-950",
    infoClass: "text-stone-800 [&>div]:border-rose-200",
    instructionsClass: "text-stone-600",
    continuedHeaderClass: "border-rose-200 text-rose-700",
    mainClass: "font-serif",
    passageTitleClass: "text-rose-900",
    passageClass: "border-rose-200 bg-white/70",
    itemClass: "",
    numberClass: "font-serif text-rose-900",
    metaClass: "text-stone-500",
    questionClass: "font-serif text-stone-950",
    optionNumberClass: "text-rose-800",
    optionRowClass: "",
    answerLineClass: "border-rose-200",
    teacherNoteClass: "bg-rose-50 text-rose-900",
    footerClass: "text-rose-400",
    logoFrameClass: "border-rose-200 bg-white",
  },
  colorband: {
    pageClass: "bg-white text-slate-950 ring-cyan-200",
    innerClass: "before:absolute before:left-0 before:top-0 before:h-full before:w-3 before:bg-cyan-500 before:content-['']",
    headerClass: "rounded-xl bg-cyan-50 px-4 py-3",
    headerLineClass: "border-cyan-400",
    subtitleClass: "text-cyan-700",
    titleClass: "text-cyan-950",
    infoClass: "text-cyan-900 [&>div]:border-cyan-200",
    instructionsClass: "text-cyan-700",
    continuedHeaderClass: "border-cyan-200 text-cyan-600",
    mainClass: "",
    passageTitleClass: "text-cyan-700",
    passageClass: "border-cyan-200 bg-cyan-50/70",
    itemClass: "",
    numberClass: "rounded bg-cyan-600 px-1.5 py-0.5 text-white",
    metaClass: "text-cyan-600",
    questionClass: "text-slate-950",
    optionNumberClass: "text-cyan-700",
    optionRowClass: "border-l-2 border-cyan-200 pl-1.5",
    answerLineClass: "border-cyan-200",
    teacherNoteClass: "bg-cyan-50 text-cyan-900",
    footerClass: "text-cyan-500",
    logoFrameClass: "border-cyan-200 bg-white",
  },
};
