import type { DesignTemplate } from "./types";

/**
 * Classic — 전통 교과서 느낌, serif 헤더, 단순 박스, 차분한 톤.
 */
export const classicTemplate: DesignTemplate = {
  id: "classic",
  label: "클래식",
  description: "전통 교과서 스타일. 차분한 톤과 명확한 위계.",
  thumbnail: "/templates/classic.png",
  theme: {
    paletteName: "classic-navy",
    primary: "#1E3A8A",
    accent: "#9F1239",
    surface: "#FAFAF9",
    textOnSurface: "#1C1917",
    muted: "#78716C",
    fontFamily: '"Paperlogy", "Pretendard", sans-serif',
    fontScale: 1,
  },
  pages: [
    {
      pageNumber: 1,
      background: { color: "#FFFFFF", pattern: "none" },
      margin: { top: 16, right: 14, bottom: 14, left: 14 },
      slots: [
        {
          slotId: "p1-header",
          blockKind: "header",
          sourceKind: "passageMeta",
          x: 14,
          y: 16,
          w: 182,
          h: 22,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 15,
            fontWeight: 700,
            textAlign: "center",
            borderColor: "#1E3A8A",
            borderWidth: 2,
            color: "#1E3A8A",
          },
          hint: "중앙 정렬 타이틀 + 하단 굵은 선",
        },
        {
          slotId: "p1-passage",
          blockKind: "passage-body",
          sourceKind: "passageBody",
          x: 14,
          y: 42,
          w: 182,
          h: 180,
          defaultStyle: {
            paddingMm: 4,
            fontSize: 10,
            color: "#1C1917",
          },
          hint: "본문 풀폭",
        },
        {
          slotId: "p1-summary",
          blockKind: "summary-callout",
          sourceKind: "summary",
          x: 14,
          y: 226,
          w: 182,
          h: 58,
          defaultStyle: {
            backgroundColor: "#FAFAF9",
            borderColor: "#1E3A8A",
            borderWidth: 1,
            paddingMm: 4,
            fontSize: 9,
            color: "#1C1917",
          },
          hint: "지문 요지",
        },
      ],
    },
    {
      pageNumber: 2,
      background: { color: "#FFFFFF", pattern: "none" },
      margin: { top: 16, right: 14, bottom: 14, left: 14 },
      slots: [
        {
          slotId: "p2-vocab-title",
          blockKind: "divider",
          sourceKind: "decorative",
          x: 14,
          y: 16,
          w: 182,
          h: 8,
          defaultStyle: { color: "#1E3A8A" },
          hint: "어휘 정리 섹션",
        },
        {
          slotId: "p2-glossary",
          blockKind: "glossary-table",
          sourceKind: "vocab",
          x: 14,
          y: 28,
          w: 182,
          h: 130,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 9,
            borderColor: "#D6D3D1",
            borderWidth: 1,
          },
          hint: "어휘 표 (영단어/품사/뜻/예문)",
        },
        {
          slotId: "p2-grammar-1",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 14,
          y: 164,
          w: 182,
          h: 58,
          defaultStyle: {
            backgroundColor: "#FAFAF9",
            paddingMm: 4,
            fontSize: 9,
            borderColor: "#D6D3D1",
            borderWidth: 1,
          },
          hint: "문법 포인트 1",
        },
        {
          slotId: "p2-grammar-2",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 14,
          y: 226,
          w: 182,
          h: 58,
          defaultStyle: {
            backgroundColor: "#FAFAF9",
            paddingMm: 4,
            fontSize: 9,
            borderColor: "#D6D3D1",
            borderWidth: 1,
          },
          hint: "문법 포인트 2",
        },
      ],
    },
    {
      pageNumber: 3,
      background: { color: "#FFFFFF", pattern: "none" },
      margin: { top: 16, right: 14, bottom: 14, left: 14 },
      slots: [
        {
          slotId: "p3-syntax-title",
          blockKind: "divider",
          sourceKind: "decorative",
          x: 14,
          y: 16,
          w: 182,
          h: 8,
          defaultStyle: { color: "#1E3A8A" },
        },
        {
          slotId: "p3-syntax",
          blockKind: "syntax-breakdown",
          sourceKind: "syntax",
          x: 14,
          y: 28,
          w: 182,
          h: 90,
          defaultStyle: {
            paddingMm: 4,
            fontSize: 9,
            borderColor: "#D6D3D1",
            borderWidth: 1,
          },
          hint: "주요 문장 구문 분석",
        },
        {
          slotId: "p3-analysis",
          blockKind: "analysis-box",
          sourceKind: "logicFlow",
          x: 14,
          y: 122,
          w: 182,
          h: 80,
          defaultStyle: {
            paddingMm: 4,
            fontSize: 9,
            borderColor: "#D6D3D1",
            borderWidth: 1,
          },
          hint: "논리 흐름 분석",
        },
        {
          slotId: "p3-exam",
          blockKind: "question",
          sourceKind: "examPoint",
          x: 14,
          y: 206,
          w: 182,
          h: 78,
          defaultStyle: {
            backgroundColor: "#FAFAF9",
            paddingMm: 4,
            fontSize: 9,
            borderColor: "#9F1239",
            borderWidth: 1,
          },
          hint: "예상 출제 포인트",
        },
      ],
    },
  ],
  extraPage: (pageNumber, { primaryKind }) => ({
    pageNumber,
    background: { color: "#FFFFFF", pattern: "none" },
    margin: { top: 16, right: 14, bottom: 14, left: 14 },
    slots: [
      {
        slotId: `p${pageNumber}-extra-${primaryKind}`,
        blockKind: primaryKind,
        x: 14,
        y: 16,
        w: 182,
        h: 268,
        defaultStyle: {
          paddingMm: 4,
          fontSize: 9,
          borderColor: "#D6D3D1",
          borderWidth: 1,
        },
      },
    ],
  }),
};
