import type { DesignTemplate } from "./types";

/**
 * Exam Sheet — 시험지 단순함, 흑백 위주, 정형.
 *
 * 시험지처럼 절제된 디자인. 컬러 최소화, 텍스트 정보량 최대화.
 */
export const examSheetTemplate: DesignTemplate = {
  id: "exam-sheet",
  label: "시험지",
  description: "시험지처럼 절제된 디자인. 정보량 최대, 컬러 최소.",
  thumbnail: "/templates/exam-sheet.png",
  theme: {
    paletteName: "exam-mono",
    primary: "#0F172A",
    accent: "#0F172A",
    surface: "#FFFFFF",
    textOnSurface: "#0F172A",
    muted: "#475569",
    fontFamily: '"Paperlogy", "Pretendard", sans-serif',
    fontScale: 0.95,
  },
  pages: [
    {
      pageNumber: 1,
      background: { color: "#FFFFFF", pattern: "none" },
      margin: { top: 12, right: 10, bottom: 10, left: 10 },
      slots: [
        {
          slotId: "p1-header",
          blockKind: "header",
          sourceKind: "passageMeta",
          x: 10,
          y: 12,
          w: 190,
          h: 16,
          defaultStyle: {
            paddingMm: 2,
            fontSize: 11,
            fontWeight: 700,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
            textAlign: "center",
          },
          hint: "최소 메타 정보 (지문번호 / 학교 / 단원)",
        },
        {
          slotId: "p1-passage",
          blockKind: "passage-body",
          sourceKind: "passageBody",
          x: 10,
          y: 32,
          w: 190,
          h: 168,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 10,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
          },
          hint: "본문 - 박스 안 빽빽하게",
        },
        {
          slotId: "p1-summary",
          blockKind: "summary-callout",
          sourceKind: "summary",
          x: 10,
          y: 204,
          w: 190,
          h: 28,
          defaultStyle: {
            paddingMm: 2,
            fontSize: 9,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
          },
          hint: "요지 한 줄",
        },
        {
          slotId: "p1-vocab-strip",
          blockKind: "vocab-grid",
          sourceKind: "vocab",
          x: 10,
          y: 236,
          w: 190,
          h: 52,
          defaultStyle: {
            paddingMm: 2,
            fontSize: 8,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
          },
          hint: "어휘 4열 그리드 - 정보 밀집",
        },
      ],
    },
    {
      pageNumber: 2,
      background: { color: "#FFFFFF", pattern: "none" },
      margin: { top: 12, right: 10, bottom: 10, left: 10 },
      slots: [
        {
          slotId: "p2-glossary",
          blockKind: "glossary-table",
          sourceKind: "vocab",
          x: 10,
          y: 12,
          w: 190,
          h: 110,
          defaultStyle: {
            paddingMm: 2,
            fontSize: 8,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
          },
          hint: "어휘 풀세트 표",
        },
        {
          slotId: "p2-grammar-1",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 10,
          y: 126,
          w: 92,
          h: 70,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 9,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
          },
        },
        {
          slotId: "p2-grammar-2",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 108,
          y: 126,
          w: 92,
          h: 70,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 9,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
          },
        },
        {
          slotId: "p2-grammar-3",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 10,
          y: 200,
          w: 92,
          h: 70,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 9,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
          },
        },
        {
          slotId: "p2-grammar-4",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 108,
          y: 200,
          w: 92,
          h: 70,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 9,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
          },
        },
      ],
    },
    {
      pageNumber: 3,
      background: { color: "#FFFFFF", pattern: "none" },
      margin: { top: 12, right: 10, bottom: 10, left: 10 },
      slots: [
        {
          slotId: "p3-syntax-1",
          blockKind: "syntax-breakdown",
          sourceKind: "syntax",
          x: 10,
          y: 12,
          w: 190,
          h: 76,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 9,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
          },
        },
        {
          slotId: "p3-syntax-2",
          blockKind: "syntax-breakdown",
          sourceKind: "syntax",
          x: 10,
          y: 92,
          w: 190,
          h: 76,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 9,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
          },
        },
        {
          slotId: "p3-analysis",
          blockKind: "analysis-box",
          sourceKind: "logicFlow",
          x: 10,
          y: 172,
          w: 190,
          h: 56,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 9,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 1,
          },
        },
        {
          slotId: "p3-exam",
          blockKind: "question",
          sourceKind: "examPoint",
          x: 10,
          y: 232,
          w: 190,
          h: 56,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 9,
            color: "#0F172A",
            borderColor: "#0F172A",
            borderWidth: 2,
          },
          hint: "예상 출제 — 굵은 테두리 강조",
        },
      ],
    },
  ],
  extraPage: (pageNumber, { primaryKind }) => ({
    pageNumber,
    background: { color: "#FFFFFF", pattern: "none" },
    margin: { top: 12, right: 10, bottom: 10, left: 10 },
    slots: [
      {
        slotId: `p${pageNumber}-extra-${primaryKind}`,
        blockKind: primaryKind,
        x: 10,
        y: 12,
        w: 190,
        h: 274,
        defaultStyle: {
          paddingMm: 3,
          fontSize: 9,
          color: "#0F172A",
          borderColor: "#0F172A",
          borderWidth: 1,
        },
      },
    ],
  }),
};
