import type { DesignTemplate } from "./types";

/**
 * Magazine — 다단 레이아웃, 강한 타이포, 컬러풀.
 *
 * 잡지/매거진 스타일. 어휘는 3열 카드 그리드로 시각적 임팩트.
 */
export const magazineTemplate: DesignTemplate = {
  id: "magazine",
  label: "매거진",
  description: "다단 레이아웃과 강한 타이포. 시각적 임팩트로 학생 시선을 끄는 자료.",
  thumbnail: "/templates/magazine.png",
  theme: {
    paletteName: "magazine-coral",
    primary: "#DC2626",
    accent: "#0891B2",
    surface: "#FFF7ED",
    textOnSurface: "#171717",
    muted: "#737373",
    fontFamily: '"Paperlogy", "Pretendard", sans-serif',
    fontScale: 1.05,
  },
  pages: [
    {
      pageNumber: 1,
      background: { color: "#FFFFFF", pattern: "none" },
      margin: { top: 10, right: 10, bottom: 10, left: 10 },
      slots: [
        {
          slotId: "p1-header-block",
          blockKind: "header",
          sourceKind: "passageMeta",
          x: 10,
          y: 10,
          w: 90,
          h: 60,
          defaultStyle: {
            backgroundColor: "#DC2626",
            color: "#FFFFFF",
            paddingMm: 6,
            borderRadius: 0,
            fontSize: 22,
            fontWeight: 900,
          },
          hint: "큰 컬러 박스 + 굵은 타이틀",
        },
        {
          slotId: "p1-summary-hero",
          blockKind: "summary-callout",
          sourceKind: "summary",
          x: 104,
          y: 10,
          w: 96,
          h: 60,
          defaultStyle: {
            backgroundColor: "#FFF7ED",
            paddingMm: 5,
            fontSize: 11,
            fontWeight: 600,
            color: "#171717",
          },
          hint: "한 줄 요약 강조",
        },
        {
          slotId: "p1-passage-col1",
          blockKind: "passage-body",
          sourceKind: "passageBody",
          x: 10,
          y: 76,
          w: 92,
          h: 212,
          defaultStyle: {
            paddingMm: 4,
            fontSize: 9,
            color: "#171717",
            lineHeight: 1.5,
          } as never,
          hint: "본문 1단 — 좌측",
        },
        {
          slotId: "p1-vocab-side",
          blockKind: "vocab-grid",
          sourceKind: "vocab",
          x: 106,
          y: 76,
          w: 94,
          h: 145,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            paddingMm: 3,
            fontSize: 8,
            borderColor: "#DC2626",
            borderWidth: 0,
          },
          hint: "어휘 6~9개 컬러 카드",
        },
        {
          slotId: "p1-grammar-snippet",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 106,
          y: 225,
          w: 94,
          h: 63,
          defaultStyle: {
            backgroundColor: "#0891B2",
            color: "#FFFFFF",
            paddingMm: 4,
            fontSize: 9,
            fontWeight: 700,
          },
          hint: "킬러 문법 1개 강조",
        },
      ],
    },
    {
      pageNumber: 2,
      background: { color: "#FFF7ED", pattern: "none" },
      margin: { top: 10, right: 10, bottom: 10, left: 10 },
      slots: [
        {
          slotId: "p2-title",
          blockKind: "divider",
          sourceKind: "decorative",
          x: 10,
          y: 10,
          w: 200,
          h: 10,
          defaultStyle: { color: "#DC2626" },
        },
        {
          slotId: "p2-grammar-1",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 10,
          y: 26,
          w: 60,
          h: 90,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            paddingMm: 4,
            fontSize: 8,
            borderRadius: 0,
          },
          hint: "문법 카드 1 (3열 그리드 중 하나)",
        },
        {
          slotId: "p2-grammar-2",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 75,
          y: 26,
          w: 60,
          h: 90,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            paddingMm: 4,
            fontSize: 8,
            borderRadius: 0,
          },
        },
        {
          slotId: "p2-grammar-3",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 140,
          y: 26,
          w: 60,
          h: 90,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            paddingMm: 4,
            fontSize: 8,
            borderRadius: 0,
          },
        },
        {
          slotId: "p2-syntax-hero",
          blockKind: "syntax-breakdown",
          sourceKind: "syntax",
          x: 10,
          y: 122,
          w: 190,
          h: 78,
          defaultStyle: {
            backgroundColor: "#171717",
            color: "#FFFFFF",
            paddingMm: 5,
            fontSize: 10,
          },
          hint: "킬러 문장 1개 강조 분석",
        },
        {
          slotId: "p2-analysis",
          blockKind: "analysis-box",
          sourceKind: "logicFlow",
          x: 10,
          y: 206,
          w: 190,
          h: 82,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            paddingMm: 4,
            fontSize: 9,
          },
          hint: "논리 흐름 + 연결어",
        },
      ],
    },
    {
      pageNumber: 3,
      background: { color: "#FFFFFF", pattern: "none" },
      margin: { top: 10, right: 10, bottom: 10, left: 10 },
      slots: [
        {
          slotId: "p3-exam-hero",
          blockKind: "question",
          sourceKind: "examPoint",
          x: 10,
          y: 10,
          w: 200,
          h: 130,
          defaultStyle: {
            backgroundColor: "#DC2626",
            color: "#FFFFFF",
            paddingMm: 6,
            fontSize: 11,
          },
          hint: "예상 출제 — 큰 박스 강조",
        },
        {
          slotId: "p3-glossary",
          blockKind: "glossary-table",
          sourceKind: "vocab",
          x: 10,
          y: 148,
          w: 200,
          h: 140,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 8,
          },
          hint: "추가 어휘 표",
        },
      ],
    },
  ],
  extraPage: (pageNumber, { primaryKind }) => ({
    pageNumber,
    background: { color: "#FFF7ED", pattern: "none" },
    margin: { top: 10, right: 10, bottom: 10, left: 10 },
    slots: [
      {
        slotId: `p${pageNumber}-extra-${primaryKind}`,
        blockKind: primaryKind,
        x: 10,
        y: 10,
        w: 200,
        h: 277,
        defaultStyle: {
          backgroundColor: "#FFFFFF",
          paddingMm: 4,
          fontSize: 9,
        },
      },
    ],
  }),
};
