import type { DesignTemplate } from "./types";

/**
 * Modern — 깔끔한 그리드, 강한 컬러 액센트, sans-serif 위주.
 *
 * 페이지 구성:
 *   p1: 헤더(상단 풀폭 컬러바) + 본문(좌 60%) + 어휘 그리드(우 40%)
 *   p2: 문법 카드 그리드(2열) + 요약 콜아웃 하단
 *   p3: 구문 분석 + 출제 포인트
 *   추가 페이지: 어휘/문법 청크
 */
export const modernTemplate: DesignTemplate = {
  id: "modern",
  label: "모던",
  description: "깔끔한 그리드와 강한 컬러 액센트. 모범적이고 명료한 학습지.",
  thumbnail: "/templates/modern.png",
  theme: {
    paletteName: "modern-blue",
    primary: "#2563EB",
    accent: "#10B981",
    surface: "#F8FAFC",
    textOnSurface: "#0F172A",
    muted: "#64748B",
    fontFamily: "Pretendard",
    fontScale: 1,
  },
  pages: [
    {
      pageNumber: 1,
      background: { color: "#FFFFFF", pattern: "none" },
      margin: { top: 14, right: 12, bottom: 12, left: 12 },
      slots: [
        {
          slotId: "p1-header",
          blockKind: "header",
          sourceKind: "passageMeta",
          x: 12,
          y: 14,
          w: 186,
          h: 26,
          defaultStyle: {
            backgroundColor: "#2563EB",
            color: "#FFFFFF",
            paddingMm: 5,
            borderRadius: 4,
            fontSize: 16,
            fontWeight: 800,
          },
          hint: "지문 제목 + 학교/학년/단원 + 액센트 색상",
        },
        {
          slotId: "p1-passage",
          blockKind: "passage-body",
          sourceKind: "passageBody",
          x: 12,
          y: 44,
          w: 110,
          h: 240,
          defaultStyle: {
            paddingMm: 4,
            fontSize: 10,
            color: "#0F172A",
          },
          hint: "본문 전체 — 번역 토글, 인라인 하이라이트 마킹",
        },
        {
          slotId: "p1-vocab-primary",
          blockKind: "vocab-grid",
          sourceKind: "vocab",
          x: 126,
          y: 44,
          w: 72,
          h: 130,
          defaultStyle: {
            backgroundColor: "#F8FAFC",
            paddingMm: 4,
            borderRadius: 4,
            fontSize: 9,
          },
          hint: "지문 핵심 어휘 6~8개, 1열 카드",
        },
        {
          slotId: "p1-summary",
          blockKind: "summary-callout",
          sourceKind: "summary",
          x: 126,
          y: 178,
          w: 72,
          h: 106,
          defaultStyle: {
            backgroundColor: "#ECFDF5",
            borderColor: "#10B981",
            borderWidth: 0,
            paddingMm: 4,
            borderRadius: 4,
            fontSize: 9,
          },
          hint: "핵심 요지 1~2문장 + 논리 흐름",
        },
      ],
    },
    {
      pageNumber: 2,
      background: { color: "#FFFFFF", pattern: "none" },
      margin: { top: 14, right: 12, bottom: 12, left: 12 },
      slots: [
        {
          slotId: "p2-grammar-1",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 12,
          y: 14,
          w: 92,
          h: 90,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            borderColor: "#E2E8F0",
            borderWidth: 1,
            borderRadius: 4,
            paddingMm: 4,
            fontSize: 9,
          },
          hint: "문법/어법 포인트 1",
        },
        {
          slotId: "p2-grammar-2",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 108,
          y: 14,
          w: 92,
          h: 90,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            borderColor: "#E2E8F0",
            borderWidth: 1,
            borderRadius: 4,
            paddingMm: 4,
            fontSize: 9,
          },
          hint: "문법/어법 포인트 2",
        },
        {
          slotId: "p2-grammar-3",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 12,
          y: 108,
          w: 92,
          h: 90,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            borderColor: "#E2E8F0",
            borderWidth: 1,
            borderRadius: 4,
            paddingMm: 4,
            fontSize: 9,
          },
          hint: "문법/어법 포인트 3",
        },
        {
          slotId: "p2-grammar-4",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 108,
          y: 108,
          w: 92,
          h: 90,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            borderColor: "#E2E8F0",
            borderWidth: 1,
            borderRadius: 4,
            paddingMm: 4,
            fontSize: 9,
          },
          hint: "문법/어법 포인트 4",
        },
        {
          slotId: "p2-analysis",
          blockKind: "analysis-box",
          sourceKind: "logicFlow",
          x: 12,
          y: 202,
          w: 188,
          h: 82,
          defaultStyle: {
            backgroundColor: "#EFF6FF",
            paddingMm: 5,
            borderRadius: 4,
            fontSize: 9,
          },
          hint: "지문 논리 흐름 + 연결어 분석",
        },
      ],
    },
    {
      pageNumber: 3,
      background: { color: "#FFFFFF", pattern: "none" },
      margin: { top: 14, right: 12, bottom: 12, left: 12 },
      slots: [
        {
          slotId: "p3-syntax-header",
          blockKind: "divider",
          sourceKind: "decorative",
          x: 12,
          y: 14,
          w: 186,
          h: 8,
          defaultStyle: { color: "#2563EB" },
          hint: "구문 분석 섹션 구분",
        },
        {
          slotId: "p3-syntax-1",
          blockKind: "syntax-breakdown",
          sourceKind: "syntax",
          x: 12,
          y: 26,
          w: 186,
          h: 80,
          defaultStyle: {
            backgroundColor: "#F8FAFC",
            paddingMm: 4,
            borderRadius: 4,
            fontSize: 9,
          },
          hint: "어려운 문장 1",
        },
        {
          slotId: "p3-syntax-2",
          blockKind: "syntax-breakdown",
          sourceKind: "syntax",
          x: 12,
          y: 110,
          w: 186,
          h: 80,
          defaultStyle: {
            backgroundColor: "#F8FAFC",
            paddingMm: 4,
            borderRadius: 4,
            fontSize: 9,
          },
          hint: "어려운 문장 2",
        },
        {
          slotId: "p3-exam",
          blockKind: "question",
          sourceKind: "examPoint",
          x: 12,
          y: 194,
          w: 186,
          h: 90,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            borderColor: "#2563EB",
            borderWidth: 2,
            borderRadius: 4,
            paddingMm: 5,
            fontSize: 9,
          },
          hint: "예상 출제 포인트 / 변형 예시",
        },
      ],
    },
  ],
  extraPage: (pageNumber, { primaryKind }) => ({
    pageNumber,
    background: { color: "#FFFFFF", pattern: "none" },
    margin: { top: 14, right: 12, bottom: 12, left: 12 },
    slots: [
      {
        slotId: `p${pageNumber}-extra-${primaryKind}`,
        blockKind: primaryKind,
        x: 12,
        y: 14,
        w: 186,
        h: 270,
        defaultStyle: {
          backgroundColor: "#F8FAFC",
          paddingMm: 4,
          borderRadius: 4,
          fontSize: 9,
        },
        hint: "추가 콘텐츠 (어휘/문법 청크)",
      },
    ],
  }),
};
