import type { DesignTemplate } from "./types";

/**
 * Notebook — 손글씨/노트 느낌, 줄노트 배경, 포스트잇 스타일.
 *
 * 살짝 기울인 포스트잇 박스로 노트 필기 느낌. 친근하고 외우기 좋은 분위기.
 * 팔레트는 쿨 민트/틸 계열 (amber/orange 미사용) — 줄노트 질감으로 정체성 유지.
 */
export const notebookTemplate: DesignTemplate = {
  id: "notebook",
  label: "노트북",
  description: "줄노트 배경 + 포스트잇 스타일. 친근하고 외우기 좋은 분위기.",
  thumbnail: "/templates/notebook.png",
  theme: {
    paletteName: "notebook-cool",
    primary: "#0D9488",
    accent: "#0369A1",
    surface: "#F0FDFA",
    textOnSurface: "#1F2937",
    muted: "#6B7280",
    fontFamily: "Pretendard",
    fontScale: 1,
  },
  pages: [
    {
      pageNumber: 1,
      background: { color: "#F0FDFA", pattern: "lines", patternColor: "#99F6E4" },
      margin: { top: 14, right: 12, bottom: 12, left: 12 },
      slots: [
        {
          slotId: "p1-header",
          blockKind: "header",
          sourceKind: "passageMeta",
          x: 12,
          y: 14,
          w: 186,
          h: 24,
          defaultStyle: {
            color: "#0D9488",
            paddingMm: 3,
            fontSize: 16,
            fontWeight: 800,
            borderColor: "#0D9488",
            borderWidth: 0,
          },
          hint: "손글씨 느낌 타이틀",
        },
        {
          slotId: "p1-passage",
          blockKind: "passage-body",
          sourceKind: "passageBody",
          x: 12,
          y: 42,
          w: 122,
          h: 242,
          defaultStyle: {
            paddingMm: 3,
            fontSize: 10,
            color: "#1F2937",
          },
          hint: "본문 - 줄노트 위에 자연스럽게",
        },
        {
          slotId: "p1-postit-summary",
          blockKind: "summary-callout",
          sourceKind: "summary",
          x: 138,
          y: 42,
          w: 60,
          h: 60,
          rotation: -2,
          defaultStyle: {
            backgroundColor: "#A7F3D0",
            paddingMm: 4,
            fontSize: 9,
            color: "#1F2937",
            shadow: "soft",
          },
          hint: "포스트잇 - 핵심 요지 (살짝 기울임)",
        },
        {
          slotId: "p1-postit-vocab",
          blockKind: "vocab-grid",
          sourceKind: "vocab",
          x: 138,
          y: 110,
          w: 60,
          h: 100,
          rotation: 1.5,
          defaultStyle: {
            backgroundColor: "#FECACA",
            paddingMm: 4,
            fontSize: 8,
            color: "#1F2937",
            shadow: "soft",
          },
          hint: "포스트잇 - 핵심 어휘 4~5개",
        },
        {
          slotId: "p1-postit-grammar",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 138,
          y: 218,
          w: 60,
          h: 66,
          rotation: -1,
          defaultStyle: {
            backgroundColor: "#BFDBFE",
            paddingMm: 4,
            fontSize: 8,
            color: "#1F2937",
            shadow: "soft",
          },
          hint: "포스트잇 - 문법 1개",
        },
      ],
    },
    {
      pageNumber: 2,
      background: { color: "#F0FDFA", pattern: "lines", patternColor: "#99F6E4" },
      margin: { top: 14, right: 12, bottom: 12, left: 12 },
      slots: [
        {
          slotId: "p2-section",
          blockKind: "divider",
          sourceKind: "decorative",
          x: 12,
          y: 14,
          w: 186,
          h: 8,
          defaultStyle: { color: "#0D9488" },
          hint: "어휘/문법 정리 섹션",
        },
        {
          slotId: "p2-glossary",
          blockKind: "glossary-table",
          sourceKind: "vocab",
          x: 12,
          y: 26,
          w: 186,
          h: 130,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            paddingMm: 3,
            fontSize: 9,
          },
          hint: "어휘 풀세트 표",
        },
        {
          slotId: "p2-grammar-1",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 12,
          y: 162,
          w: 90,
          h: 62,
          rotation: -0.5,
          defaultStyle: {
            backgroundColor: "#DBEAFE",
            paddingMm: 3,
            fontSize: 9,
            shadow: "soft",
          },
        },
        {
          slotId: "p2-grammar-2",
          blockKind: "grammar-card",
          sourceKind: "grammar",
          x: 108,
          y: 162,
          w: 90,
          h: 62,
          rotation: 0.5,
          defaultStyle: {
            backgroundColor: "#A7F3D0",
            paddingMm: 3,
            fontSize: 9,
            shadow: "soft",
          },
        },
        {
          slotId: "p2-analysis",
          blockKind: "analysis-box",
          sourceKind: "logicFlow",
          x: 12,
          y: 230,
          w: 186,
          h: 54,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            paddingMm: 3,
            fontSize: 9,
          },
          hint: "논리 흐름 정리",
        },
      ],
    },
    {
      pageNumber: 3,
      background: { color: "#F0FDFA", pattern: "lines", patternColor: "#99F6E4" },
      margin: { top: 14, right: 12, bottom: 12, left: 12 },
      slots: [
        {
          slotId: "p3-syntax-1",
          blockKind: "syntax-breakdown",
          sourceKind: "syntax",
          x: 12,
          y: 14,
          w: 186,
          h: 90,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            paddingMm: 4,
            fontSize: 9,
            shadow: "soft",
          },
        },
        {
          slotId: "p3-syntax-2",
          blockKind: "syntax-breakdown",
          sourceKind: "syntax",
          x: 12,
          y: 108,
          w: 186,
          h: 90,
          defaultStyle: {
            backgroundColor: "#FFFFFF",
            paddingMm: 4,
            fontSize: 9,
            shadow: "soft",
          },
        },
        {
          slotId: "p3-exam",
          blockKind: "question",
          sourceKind: "examPoint",
          x: 12,
          y: 202,
          w: 186,
          h: 82,
          defaultStyle: {
            backgroundColor: "#CCFBF1",
            paddingMm: 4,
            fontSize: 9,
            shadow: "soft",
          },
          hint: "예상 출제",
        },
      ],
    },
  ],
  extraPage: (pageNumber, { primaryKind }) => ({
    pageNumber,
    background: { color: "#F0FDFA", pattern: "lines", patternColor: "#99F6E4" },
    margin: { top: 14, right: 12, bottom: 12, left: 12 },
    slots: [
      {
        slotId: `p${pageNumber}-extra-${primaryKind}`,
        blockKind: primaryKind,
        x: 12,
        y: 14,
        w: 186,
        h: 270,
        defaultStyle: {
          backgroundColor: "#FFFFFF",
          paddingMm: 4,
          fontSize: 9,
        },
      },
    ],
  }),
};
