/**
 * Scans public/recordings/*.timeline.json and regenerates remotion/guideManifest.ts,
 * which Root.tsx imports to register one Remotion composition per recorded flow.
 * Embeds data as TS (not JSON import) to avoid bundler/tsconfig resolveJsonModule issues.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const REC_DIR = join(process.cwd(), "public", "recordings");
const OUT = join(process.cwd(), "remotion", "guideManifest.ts");

export async function regenerateManifest(): Promise<void> {
  let files: string[] = [];
  try {
    files = (await readdir(REC_DIR)).filter((f) => f.endsWith(".timeline.json"));
  } catch {
    /* no recordings yet */
  }
  const entries = [];
  for (const f of files.sort()) {
    const data = JSON.parse(await readFile(join(REC_DIR, f), "utf8"));
    entries.push(data);
  }
  const banner = "// AUTO-GENERATED by scripts/demo/manifest.ts — do not edit by hand.\n";
  const body =
    `export type GuideMark =\n` +
    `  | { tMs: number; type: "caption"; text: string; subtitle?: string }\n` +
    `  | { tMs: number; type: "caption-clear" }\n` +
    `  | { tMs: number; type: "zoom"; rect: { x: number; y: number; width: number; height: number }; scale?: number }\n` +
    `  | { tMs: number; type: "zoom-out" }\n` +
    `  | { tMs: number; type: "highlight"; rect: { x: number; y: number; width: number; height: number } }\n` +
    `  | { tMs: number; type: "chapter"; text: string };\n\n` +
    `export type GuideEntry = { flow: string; src: string; durationMs: number; fps: number; marks: GuideMark[] };\n\n` +
    `export const GUIDE_FLOWS: GuideEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
  await writeFile(OUT, banner + body);
  // eslint-disable-next-line no-console
  console.log(`✓ manifest: ${entries.length} flow(s) → remotion/guideManifest.ts`);
}

// Allow running standalone: tsx scripts/demo/manifest.ts
if (import.meta.url === `file://${process.argv[1]}`) {
  regenerateManifest();
}
