import { KO_BLOCKING_CODES } from "@/lib/korean/quality/codes";
import { SHIP_FIRST_WARNING_CODES } from "@/lib/question-quality";

export const RELAXED_BLOCKING_QUALITY_CODES = new Set([
  "option-count",
  "duplicate-option-label",
  "duplicate-option-text",
  "empty-option-text",
  "correct-answer-mismatch",
  "wrong-option-explanation-count",
  "mid-word-marker",
  "target-not-standalone",
  "punctuation-only-chunk",
  "scrambled-already-solved",
  "grammar-marker-count",
  "grammar-render-marker-count",
  "grammar-error-count",
  "grammar-correct-answer-labels",
  "grammar-missing-error-expression",
  "grammar-error-not-mutated",
  "grammar-error-pos-change",
  "grammar-error-explanation-surface-order",
  "grammar-explanation-answer-range-leak",
  "grammar-explanation-range-shorthand",
  "grammar-answer-in-wrong-explanations",
  "grammar-obvious-pronoun-agreement",
  "grammar-obvious-noun-what-relative",
  "grammar-obvious-seem-gerund",
  "grammar-obvious-seem-to-gerund",
  "grammar-shallow-local-participle-parallel",
  "grammar-obvious-to-gerund-after-verb",
  "grammar-obvious-connector-to-what",
  "grammar-obvious-despite-being-to-be",
  "grammar-shallow-despite-although-gerund",
  "grammar-debatable-attention-to-gerund",
  "grammar-debatable-more-most-like",
  "grammar-lexical-look-like-answer",
  "grammar-debatable-sink-passive",
  "grammar-shallow-because-despite-clause",
  "grammar-obvious-modal-gerund",
  "grammar-obvious-modal-to-infinitive",
  "grammar-obvious-intransitive-passive",
  "grammar-obvious-endure-passive-object",
  "grammar-gibberish-inversion-fragment",
  "grammar-obvious-finite-to-ing-colon",
  "grammar-shallow-participle-adjective-answer",
  "grammar-obvious-double-ing",
  "grammar-obvious-local-agreement",
  "grammar-obvious-local-pronoun-agreement",
  "grammar-obvious-object-pronoun-subject",
  "grammar-obvious-before-after-to-infinitive",
  "grammar-obvious-adjacent-sv-agreement",
  "grammar-obvious-passive-to-gap-ing",
  "grammar-obvious-adverb-adjective",
  "grammar-fixed-that-is-idiom",
  "grammar-obvious-living-finite",
  "grammar-obvious-living-lived",
  "grammar-obvious-what-noun-prefix",
  "grammar-killer-thin-missing-aux",
  "grammar-debatable-who-object-decoy",
  "grammar-debatable-discourse-though-decoy",
  "grammar-demonstrative-that-way-decoy",
  "grammar-semantic-who-what-answer",
  "grammar-semantic-how-why-answer",
  "grammar-killer-thin-relative-animacy",
  "grammar-killer-thin-concessive-as",
  "grammar-weak-filler-decoys",
  "grammar-debatable-it-being-decoy",
  "grammar-explanation-self-contradictory",
  "grammar-explanation-typo",
  "grammar-noun-clause-pronoun-mislabel",
  "grammar-phrasal-verb-mislabel",
  "grammar-vague-metadata-tag",
  "grammar-look-like-complement-mislabel",
  "grammar-seem-to-complement-mislabel",
  "grammar-seem-to-object-mislabel",
  "grammar-that-way-adverb-mislabel",
  "grammar-human-made-postmodifier-mislabel",
  "grammar-basic-overloaded-design",
  "grammar-too-basic-decoys",
  "grammar-shallow-checklist-decoys",
  "grammar-shallow-depends-decoy",
  "grammar-shallow-nearby-passive-decoy",
  "grammar-shallow-than-decoy",
  "grammar-explanation-too-long-hard",
  "grammar-agreement-explanation-too-thin",
  "grammar-afford-modal-mislabel",
  "grammar-appear-adverb-mislabel",
  "grammar-appear-pointcode-voice-mismatch",
  "grammar-nonstandard-terminology",
  "grammar-marker-too-dense",
  "grammar-keypoint-token-not-source-backed",
  "grammar-keypoint-untested-token",
  "grammar-mixed-as-it-span",
  "grammar-decoy-point-diversity",
  "grammar-killer-answer-point-repeated",
  "grammar-killer-thin-answer",
  "grammar-killer-generic-answer-point",
  // 절/문장 통째 밑줄(예: 프리미엄 실측 "these digital platforms create a trusting
  // environment" 7단어)은 정답성·가독성을 해치는 명백한 결함 — relaxed 폴백에서도
  // 출하 금지. ('wide'는 strict 전용이라 의도적으로 제외 — 완전 실패 방지.)
  "grammar-underline-too-long",
  "grammar-underline-punctuated-fragment",
  // 복수정답 시비(규범 논쟁 자리 밑줄)는 relaxed 폴백에서도 출하 금지 —
  // 정답 무효급 결함이라 미생성이 잘못된 문항보다 낫다.
  "grammar-disputed-usage-target",
  // 정답 노출/타깃 부적격도 같은 이유로 relaxed에서 출하 금지
  // (2026-06-12 사용자 테스트에서 relaxed 누수 실측: 노출 5건·list-like 1건).
  "multi-blank-answer-visible",
  "blank-target-list-like",
  "vocab-option-word-mismatch",
  // 부분구 누설(빈칸 값 핵심부 잔존)·어휘 원단어 잔존도 정답 노출이라 차단
  // (2026-06-12 적대검수 추가 발견).
  "multi-blank-answer-partial-visible",
  "vocab-source-word-visible",
  // 마커 깨짐(인접 중복)·오배치(엉뚱한 동형 단어)도 정답 노출/해설 불일치라
  // relaxed에서도 차단 (2026-06-12 어법 KILLER 30개 중 실측 2건).
  "grammar-marker-adjacent-duplicate",
  "grammar-marker-context-mismatch",
  "grammar-surrounding-missing-marker",
  // 시제 단독변경(realizes↔realized)은 문맥상 두 시제 가능 = 정답 시비. 차단.
  "grammar-tense-only-error",
  // 수량(m) 시비형 정답 — 의미토글(little↔a little)·양용명사·규범논쟁(less/fewer)은
  // 둘 다 정문/문맥의존이라 복수정답 시비. relaxed 폴백에서도 출하 금지(적대검증 2026-06-23).
  "grammar-quantity-meaning-toggle",
  "grammar-quantity-ambiguous-noun",
  "grammar-quantity-debatable",
  // 네모 어법 — 세 슬롯 전부가 정답 키를 구성하므로 슬롯/조합 결함은 전부
  // 정답 무효급. relaxed 폴백에서도 출하 금지.
  "combo-slot-count",
  "combo-render-slot-count",
  "combo-slot-missing-candidate",
  "combo-slot-not-mutated",
  "combo-correct-not-in-source",
  "combo-option-value-mismatch",
  "combo-duplicate-option",
  "combo-answer-combo-mismatch",
  "combo-candidate-visible-elsewhere",
  "grammar-correction-underline-count",
  "grammar-correction-missing-underlined-segments",
  "grammar-correction-missing-passage-underline",
  "grammar-correction-underline-count-mismatch",
  "grammar-correction-error-count",
  "grammar-correction-missing-corrected-part",
  "grammar-correction-missing-source-text",
  "grammar-correction-missing-displayed-text",
  "grammar-correction-missing-error-part",
  "grammar-correction-not-mutated",
  "grammar-correction-correction-mismatch",
  "grammar-correction-answer-mismatch",
  "grammar-correction-corrected-part-not-in-source-text",
  "grammar-correction-error-part-not-in-displayed-text",
  "grammar-correction-displayed-not-mutated",
  "grammar-correction-underline-too-narrow",
  "grammar-correction-underlined-segment-short",
  "grammar-correction-displayed-text-not-rendered",
  "grammar-correction-source-text-not-source-backed",
  "grammar-correction-sentence-not-source-backed",
  "grammar-correction-debatable-infinitive",
  "grammar-correction-killer-thin-segment",
  "topic-option-language",
  // 정답 극성 토글(강제 설정 시에만 발생) — 발문/저장 극성이 강제값과 어긋나면
  // 정답 무효급이라 relaxed 폴백에서도 출하 금지. 미설정(기본) 경로엔 영향 없음.
  "content-match-direction-polarity",
  "content-match-type-mismatch",
  "gist-polarity-direction-mismatch",
  "gist-polarity-field-mismatch",
  "summary-mc-direction-frame",
  "summary-mc-missing-summary",
  "summary-mc-blank-marker-count",
  "summary-mc-summary-language",
  "summary-mc-missing-blank-answer",
  "summary-mc-answer-language",
  "summary-mc-awkward-collocation",
  "summary-mc-correct-answer-mismatch",
  "summary-mc-correct-pair-mismatch",
  "summary-mc-option-pair-shape",
  "summary-mc-option-language",
  "summary-mc-missing-half-correct-traps",
  // 요약문 완성(단답) — 마커 누락/정답 인라인 노출은 relaxed 폴백에서도 출하 금지(누수·렌더 파손).
  "summary-complete-missing-summary",
  "summary-complete-blank-marker-count",
  "summary-complete-answer-language",
  "summary-complete-answer-leaks-in-summary",
  // 요약문 영작(SUMMARY_WRITING) — 누수/구조 무효 게이트는 relaxed 폴백에서도
  // 출하 금지(정답 노출·placeholder 깨짐·비영어 정답은 미생성이 잘못 생성보다 낫다).
  // sw-distractor-semantic 은 warning 이라 여기 미포함.
  "sw-answer-not-in-summary",
  "sw-wordbank-no-answer-order",
  "sw-summary-blank-marker-count",
  "sw-modelanswer-present",
  "sw-answer-language",
  // 핵심 표현 빈칸(FILL_BLANK_KEY) — 빈칸 무결성/정답 노출 게이트는 relaxed 폴백에서도
  // 출하 금지(정답 자음골격 노출·빈칸 2개·정답이 본문에 비-빈칸 verbatim 잔존은
  // 미생성이 잘못 생성보다 낫다). fbk-answer-residual-leak 은 단일어일 때 warning 이라
  // 여기 있어도 차단되지 않는다(warning 은 비차단).
  "fbk-missing-blank-marker",
  "fbk-answer-skeleton-leak",
  "fbk-multiple-blanks",
  "fbk-answer-residual-leak",
  "implied-meaning-missing-expression",
  "implied-meaning-missing-underline",
  "implied-meaning-underline-count",
  "implied-meaning-option-language",
  "implied-meaning-option-not-english",
  "implied-meaning-single-word-target",
  "implied-meaning-target-too-short",
  "implied-meaning-target-not-in-passage",
  "implied-meaning-noncentral-target",
  "implied-meaning-rhetorical-question-target",
  "implied-meaning-missing-surface-meaning",
  "implied-meaning-thin-reasoning-gap",
  "implied-meaning-direct-answer-leak",
  "implied-meaning-thin-evidence-chain",
  "implied-meaning-absolute-giveaway-option",
  "irrelevant-sentence-count",
  "empty-irrelevant-sentence",
  "irrelevant-index-range",
  "irrelevant-index-edge",
  "irrelevant-answer-index-mismatch",
  "irrelevant-source-not-verbatim",
  "irrelevant-source-first-sentence",
  "irrelevant-source-order",
  "irrelevant-answer-from-source",
  "irrelevant-too-unrelated",
  "irrelevant-inserted-ungrammatical",
  "irrelevant-obvious-counterclaim-cue",
  "irrelevant-prescriptive-giveaway",
  "sentence-insert-missing-passage",
  "sentence-insert-gap-marker-count",
  "sentence-insert-omitted-source-not-backed",
  "sentence-insert-omitted-source-visible",
  "sentence-insert-given-leaks-in-passage",
  "sentence-order-missing-given",
  "sentence-order-given-too-long",
  "sentence-order-given-too-long-relative",
  "sentence-order-paragraph-count",
  "sentence-order-paragraph-labels",
  "sentence-order-paragraph-too-short",
  "sentence-order-paragraph-too-thin",
  "sentence-order-paragraph-imbalance",
  "sentence-order-option-permutation",
  "sentence-order-option-duplicates",
  "sentence-order-correct-option-shape",
  "sentence-order-unscrambled-answer",
  // These BLANK_INFERENCE paraphrase gates remain blocking even in the relaxed
  // fallback because shipping an untransformed or giveaway item is worse than
  // asking the generation loop to try again.
  "blank-missing-answer",
  "blank-paraphrase-answer-not-transformed",
  "blank-paraphrase-answer-too-verbatim",
  "blank-paraphrase-missing-answer-logic",
  "blank-paraphrase-option-source-copy",
  "blank-paraphrase-option-imbalance",
  "blank-paraphrase-correct-too-thin",
  "blank-paraphrase-difficulty-mismatch",
  "blank-paraphrase-killer-too-easy",
  "blank-paraphrase-killer-giveaway-distractors",
  "blank-paraphrase-verb-form-slot-mismatch",
  "blank-paraphrase-subject-slot-mismatch",
  "blank-paraphrase-clause-slot-mismatch",
  "blank-paraphrase-polarity-loss",
  "blank-paraphrase-target-trailing-function",
  "blank-paraphrase-target-too-wide",
  "blank-killer-target-too-easy",
  "blank-target-too-small",
  "blank-target-list-like",
  "blank-awkward-correct-option",
  "blank-awkward-option",
  "multi-blank-paraphrase-correct-source-exact",
  "negative-paraphrase-copula-slot-mismatch",
  "negative-paraphrase-stacked-prepositions",
  "negative-paraphrase-verb-slot-mismatch",
  "negative-paraphrase-modal-be-negated-complement",
  "negative-paraphrase-no-subject-double-negation",
  "double-negative-clause-missing-subject",
  "double-negative-because-phrase-slot",
]);

// KO(국어) blocking 코드 전부 등록 — 미등록 error 는 relaxed 폴백에서 warning 으로
// 강등 출하되므로(판정단 실측) 구조·정답 무결성 결함은 relaxed 에서도 차단한다
// (KO-DESIGN-SPEC §7). KO 코드는 SHIP_FIRST 에 없어 아래 차감의 영향을 받지 않는다.
for (const code of KO_BLOCKING_CODES) {
  RELAXED_BLOCKING_QUALITY_CODES.add(code);
}

// SHIP-FIRST: B(취향/난이도) 코드는 question-quality 에서 warning 으로 강등되어 절대
// error 로 이 필터에 도달하지 않는다. 단일 진실원(SHIP_FIRST_WARNING_CODES)에서 차감해
// 두 목록의 동기화를 보장하고 위 리터럴의 중복 항목(blank-target-list-like)도 제거한다.
// 남는 것 = A(차단 유지) + C(사전 fast-fail) 코드뿐.
for (const code of SHIP_FIRST_WARNING_CODES) {
  RELAXED_BLOCKING_QUALITY_CODES.delete(code);
}
